server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: HOTEL-K8S-DEMO
          uri: lb://HOTEL-K8S-DEMO
          predicates:
            - Path=/hotel/**

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka