apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-k8s-demo
  labels:
    app: hotel-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-k8s-demo
  template:
    metadata:
      labels:
        app: hotel-k8s-demo
    spec:
      containers:
        - name: hotel-k8s-demo
          image: vvsenthil/hotel-k8s-demo:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hotel-k8s-demo
spec:
  ports:
    - targetPort: 8080
      port: 80
  selector:
    app: hotel-k8s-demo
